### ISSUE TITLE
SpringTx

### ISSUE THREAD

**Issue by carlosxiao** [java-craft/interview-case#1]
`描述:`
1. 如下所示, 所有的方法都在同一个类中定义(UserService)
2. 外部调用methodB方法时, 如果内部执行method3出现异常那么 methodA方法内部调用后的结果会不会进行回滚？说明原因！
``` java
@Service
public class UserService {

	//insert操作
	public String method1(){
		//do something1 
	}
	//update操作
	public String method2(){
		//do something2
	}
	//delete操作
	public String method3(){
		//do something3
	}

	//添加事务
	@Transactional
	public void methodA(){
		method1();
		method2()
	}
	
	//添加事务
	@Transactional
	public void methodB(){
		methodA();
		method3();	//调用异常
	}
}

```

**Comment by ouyunwen** [comment]
答：会
我的理解：
1，只要抛出了异常，给spring的事务aop拦截到，整个事务都会回滚。这里的整个事务是指不管这个service方法里面调了类本身的带事务（@Transactional）方法，还是别的service带事务（@Transactional）的方法，不管这些被调用的方法的@Transactional是不是Propagation.REQUIRES_NEW，全部都会回滚。这个应该是spring的设计，所以应该没什么好展开的。
下面展开讨论下：
2，上面methodA的事务将不会起作用，这是因为跟spring的aop原理有关。spring在调用UserService 时，其实真正调的是UserService 的代理类。因为在controller层注入该service时，spring把代理类的对象注入到了这个变量。所以controller先调用该代理类的那个同名方法methodB，里面会有一些附加的代码（例如事务开启之类吧），然后，代理类里面有真正的UserService的引用，所以这时会调UserService真正的方法methodB，然后methodB会直接调用UserService 本身的methodA，由于UserService 本身不是代理类，因此不会methodA上面的注解将不会生效。
3，补充第2点，如果methodA是在别的service，那事务将会生效，因为这时调的又是一个代理类的方法。
4，如果methodA是在别的service，并且propagation = Propagation.REQUIRES_NEW，那么如果methodA设置了回滚标记，methodB只要没报异常或标记回滚，methodB还是会提交事务的。
以上是我的理解，其中第2点我是建了个springboot 2.0工程调试看的。第1和4我是在原有的springboot 1.0测试的。有不对的地方请指教。

**Comment by dengjie1986** [comment]
会回滚，事务起作用。
原因：因为方法A的事务没有额外声明开启新的事务，默认用的是B的事务。所以B事务提交，方法A的操作才能提交。回滚也是一样的，B事务回滚，A事务同样回滚。
spring事务利用的是aop实现的为UserService创建了一个代理，调用方法前开启一个事务，中间任何一个sql操作抛出异常都会被aop拦截到然后触发事务回滚。
AOP能拦截到的是代理对象的方法，而拦截不到内部调用方法。

若把methodB()的@Transactional去掉，采用非事务方法调用事务方法，则方法A的事务就不起作用了，不会回滚。
原因为如果内部调用，调用的方法没有开启事务，那么开启事务被调用的方法，事务是不会开启的，即去掉B方法的@Transactional注解，则A方法的事务是不会有作用的。
即Spring事务是采用AOP实现的，内部调用的方法没有被AOP拦截到，内部的方法是不走2次切面。

如果B方法调用的A方法在另外一个service里面，也就是不同的类，这个A方法上面加上事务注解，则会回滚，因为又有一个新的代理对象被开启了。

可见事务上都加上的传播特性，非事务方法调用内部事务方法，以及调用外部事务方法，都是不一样的结果。
